version: '2.1'
services:
  search-api:
    build: .
    image: python:3.6
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
        - ./:/app/
    ports:
        - 8000:8000
    depends_on:
      esprod1:
        condition: service_healthy
      redis-db:
        condition : service_healthy
    networks:
      - backend  

  redis-db:
    image: redis
    container_name: redis-db
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - backend

  esprod1:
    image: elasticsearch:7.8.0
    container_name: esprod1
    volumes:
        - ./data/:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
    environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "discovery.type=single-node"
    networks:
        - backend

networks:
  backend:
    driver: bridge

    # rq worker googleDown -u redis://redis & &&
    # rq worker tikaExtracot -u redis://redis &