version: '3'
services:
  search-api:
    build: .
    image: python:3.6
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
        - ./:/app/
    ports:
        - 8000:8000
    depends_on:
      - redis-db
      - esprod1
    networks:
      - backend  

  redis-db:
    image: redis
    container_name: redis-db
    networks:
      - backend

  esprod1:
    image: elasticsearch:7.8.0
    container_name: esprod1
    volumes:
        - ./data/:/usr/share/elasticsearch/data
    ports:
        - 9200:9200

    environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "discovery.type=single-node"
    networks:
        - backend

networks:
  backend:
    driver: bridge